# Generated by Django 2.1 on 2018-08-03 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('parcelado', models.BooleanField(verbose_name='Parcelado?')),
                ('qtd_parcela', models.IntegerField(verbose_name='Quantidade de Parcelas')),
                ('a_vista', models.BooleanField(verbose_name='A vista?')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('biro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_biro', to='empresa.Biro', verbose_name='biro')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_movimentacao', to='core.Compra', verbose_name='movimentacao')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_consulta', to='core.Consulta', verbose_name='biro')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('S', 'Saque'), ('T', 'Transferencia'), ('B', 'Pagamento de Boleto')], max_length=1, verbose_name='Tipo')),
                ('valor', models.FloatField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Movimentacao',
                'verbose_name_plural': 'Movimentacoes',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_movimentacao', to='core.Movimentacao', verbose_name='movimentacao'),
        ),
        migrations.AddField(
            model_name='evento',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_pessoa', to='pessoa.Pessoa', verbose_name='pessoa'),
        ),
    ]
