# Generated by Django 2.1 on 2018-08-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Bereau')),
                ('site', models.CharField(max_length=100, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Bereau',
                'verbose_name_plural': 'Bereaus',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.IntegerField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
