# Generated by Django 2.1 on 2018-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='fonte_renda',
            field=models.TextField(blank=True, null=True, verbose_name='fonte_renda'),
        ),
    ]
