# Generated by Django 2.1 on 2018-08-04 19:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Item'), size=None)),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_pessoa', to='pessoa.Pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_consulta', to='pessoa.Consulta', verbose_name='consulta')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_pessoa', to='pessoa.Pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('S', 'Saque'), ('T', 'Transferencia'), ('B', 'Pagamento de Boleto')], max_length=1, verbose_name='Tipo')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_pessoa', to='pessoa.Pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'Movimentacao',
                'verbose_name_plural': 'Movimentacoes',
            },
        ),
    ]
