# Generated by Django 2.1 on 2018-08-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20180804_1644'),
        ('pessoa', '0003_auto_20180804_1311'),
    ]

    operations = [
    ]
